/**
 * Flowtype definitions for watchify
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'watchify' {
    declare var Watchify: Watchify.Constructor;
    declare module.exports: typeof Watchify
}