// @flow
/**
 * Flowtype definitions for svg2png
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'svg2png' {
    declare module.exports: typeof svg2png
}