// @flow
/**
 * Flowtype definitions for iban
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */


/**
 * 
 * @summary  Interface for {
 * @link  IBAN} object.
 * @author  Cyril Schumacher
 * @version  1.0
 */
declare interface IBANStatic {

    /**
     * 
     * @summary  Returns the IBAN in a electronic format.
     * @param  The IBAN to convert.
     * @param  IBAN in electronic format.
     */
    electronicFormat(iban: string): string,

        /**
         * 
         * @summary  Convert the passed BBAN to an IBAN for this country specification.
         * @param  The country of the BBAN.
         * @param  The BBAN to convert to IBAN.
         * @returns  The IBAN.
         */
        fromBBAN(countryCode: string, bban: string): string,

        /**
         * 
         * @summary  Check if the passed iban is valid according to this specification.
         * @param  The iban to validate.
         * @returns  True if valid, false otherwise.
         */
        isValid(iban: string): boolean,

        /**
         * 
         * @summary  Check of the passed BBAN is valid.
         * @param  The country of the BBAN.
         * @param  The BBAN to validate.
         * @returns  True if valid, false otherwise.
         */
        isValidBBAN(countryCode: string, bban: string): boolean,

        /**
         * 
         * @summary  Returns the IBAN in a print format.
         * @param  The IBAN to convert.
         * @param  IBAN in print format.
         */
        printFormat(iban: string, separator: string[]): string,

        /**
         * 
         * @summary  Convert the passed IBAN to a country-specific BBAN.
         * @param  The IBAN to convert.
         * @param  the separator to use between BBAN blocks.
         * @returns  The BBAN
         */
        toBBAN(iban: string, separator: string[]): string
}
declare var IBAN: IBANStatic;
declare module 'iban' {
    declare module.exports: typeof IBAN
}