// @flow
/**
 * Flowtype definitions for depd
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'depd' {
    declare module.exports: typeof depd
    declare interface Deprecate {
        (message: string): void,
        function(fn: Function, message?: string): Function,
        property(obj: Object, prop: string, message: string): void
    }
}