environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  # - npm -g install yarn@latest
  # - set PATH=%APPDATA%\yarn;%PATH%
  # - yarn install
matrix:
  fast_finish: true
build: off
cache:
  - cli/.flow-bins-cache
test_script:
  - appveyor.cmd
