// @flow
/**
 * Flowtype definitions for deep-equal
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'deep-equal' {
    declare interface DeepEqualOptions {
        strict: boolean
    }
    declare     var deepEqual: (actual: Object, expected: Object, opts?: DeepEqualOptions) => boolean;
    declare module.exports: typeof deepEqual
}