// @flow
/**
 * Flowtype definitions for iniparser
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'iniparser' {
    declare     export function parse<T>(file: string, callback: (err: any, data: T) => void): void
    declare     export function parseSync<T>(file: string): T
    declare     export function parseString<T>(data: string): T
}