// flow-typed signature: 8398e76c1bcfae47be86049329f14b93
// flow-typed version: <<STUB>>/nodegit_v^0.15.1/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodegit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodegit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodegit/blame' {
  declare module.exports: any;
}

declare module 'nodegit/blob' {
  declare module.exports: any;
}

declare module 'nodegit/checkout' {
  declare module.exports: any;
}

declare module 'nodegit/cherrypick' {
  declare module.exports: any;
}

declare module 'nodegit/clone' {
  declare module.exports: any;
}

declare module 'nodegit/commit' {
  declare module.exports: any;
}

declare module 'nodegit/config' {
  declare module.exports: any;
}

declare module 'nodegit/convenient_hunks' {
  declare module.exports: any;
}

declare module 'nodegit/convenient_patch' {
  declare module.exports: any;
}

declare module 'nodegit/diff_file' {
  declare module.exports: any;
}

declare module 'nodegit/diff_line' {
  declare module.exports: any;
}

declare module 'nodegit/diff' {
  declare module.exports: any;
}

declare module 'nodegit/enums' {
  declare module.exports: any;
}

declare module 'nodegit/merge' {
  declare module.exports: any;
}

declare module 'nodegit/nodegit' {
  declare module.exports: any;
}

declare module 'nodegit/note' {
  declare module.exports: any;
}

declare module 'nodegit/object' {
  declare module.exports: any;
}

declare module 'nodegit/odb_object' {
  declare module.exports: any;
}

declare module 'nodegit/odb' {
  declare module.exports: any;
}

declare module 'nodegit/oid' {
  declare module.exports: any;
}

declare module 'nodegit/rebase' {
  declare module.exports: any;
}

declare module 'nodegit/reference' {
  declare module.exports: any;
}

declare module 'nodegit/remote' {
  declare module.exports: any;
}

declare module 'nodegit/repository' {
  declare module.exports: any;
}

declare module 'nodegit/reset' {
  declare module.exports: any;
}

declare module 'nodegit/revert' {
  declare module.exports: any;
}

declare module 'nodegit/revwalk' {
  declare module.exports: any;
}

declare module 'nodegit/signature' {
  declare module.exports: any;
}

declare module 'nodegit/stash' {
  declare module.exports: any;
}

declare module 'nodegit/status_file' {
  declare module.exports: any;
}

declare module 'nodegit/status_list' {
  declare module.exports: any;
}

declare module 'nodegit/status' {
  declare module.exports: any;
}

declare module 'nodegit/submodule' {
  declare module.exports: any;
}

declare module 'nodegit/tag' {
  declare module.exports: any;
}

declare module 'nodegit/tree_entry' {
  declare module.exports: any;
}

declare module 'nodegit/tree' {
  declare module.exports: any;
}

declare module 'nodegit/lookup_wrapper' {
  declare module.exports: any;
}

declare module 'nodegit/normalize_options' {
  declare module.exports: any;
}

declare module 'nodegit/shallow_clone' {
  declare module.exports: any;
}

declare module 'nodegit/clean' {
  declare module.exports: any;
}

declare module 'nodegit/configureLibssh2' {
  declare module.exports: any;
}

declare module 'nodegit/install' {
  declare module.exports: any;
}

declare module 'nodegit/postinstall' {
  declare module.exports: any;
}

declare module 'nodegit/preinstall' {
  declare module.exports: any;
}

declare module 'nodegit/getStatus' {
  declare module.exports: any;
}

declare module 'nodegit/buildFlags' {
  declare module.exports: any;
}

declare module 'nodegit/execPromise' {
  declare module.exports: any;
}

declare module 'nodegit/gitExecutableLocation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodegit/blame.js' {
  declare module.exports: $Exports<'nodegit/blame'>;
}
declare module 'nodegit/blob.js' {
  declare module.exports: $Exports<'nodegit/blob'>;
}
declare module 'nodegit/checkout.js' {
  declare module.exports: $Exports<'nodegit/checkout'>;
}
declare module 'nodegit/cherrypick.js' {
  declare module.exports: $Exports<'nodegit/cherrypick'>;
}
declare module 'nodegit/clone.js' {
  declare module.exports: $Exports<'nodegit/clone'>;
}
declare module 'nodegit/commit.js' {
  declare module.exports: $Exports<'nodegit/commit'>;
}
declare module 'nodegit/config.js' {
  declare module.exports: $Exports<'nodegit/config'>;
}
declare module 'nodegit/convenient_hunks.js' {
  declare module.exports: $Exports<'nodegit/convenient_hunks'>;
}
declare module 'nodegit/convenient_patch.js' {
  declare module.exports: $Exports<'nodegit/convenient_patch'>;
}
declare module 'nodegit/diff_file.js' {
  declare module.exports: $Exports<'nodegit/diff_file'>;
}
declare module 'nodegit/diff_line.js' {
  declare module.exports: $Exports<'nodegit/diff_line'>;
}
declare module 'nodegit/diff.js' {
  declare module.exports: $Exports<'nodegit/diff'>;
}
declare module 'nodegit/enums.js' {
  declare module.exports: $Exports<'nodegit/enums'>;
}
declare module 'nodegit/index' {
  declare module.exports: $Exports<'nodegit'>;
}
declare module 'nodegit/index.js' {
  declare module.exports: $Exports<'nodegit'>;
}
declare module 'nodegit/merge.js' {
  declare module.exports: $Exports<'nodegit/merge'>;
}
declare module 'nodegit/nodegit.js' {
  declare module.exports: $Exports<'nodegit/nodegit'>;
}
declare module 'nodegit/note.js' {
  declare module.exports: $Exports<'nodegit/note'>;
}
declare module 'nodegit/object.js' {
  declare module.exports: $Exports<'nodegit/object'>;
}
declare module 'nodegit/odb_object.js' {
  declare module.exports: $Exports<'nodegit/odb_object'>;
}
declare module 'nodegit/odb.js' {
  declare module.exports: $Exports<'nodegit/odb'>;
}
declare module 'nodegit/oid.js' {
  declare module.exports: $Exports<'nodegit/oid'>;
}
declare module 'nodegit/rebase.js' {
  declare module.exports: $Exports<'nodegit/rebase'>;
}
declare module 'nodegit/reference.js' {
  declare module.exports: $Exports<'nodegit/reference'>;
}
declare module 'nodegit/remote.js' {
  declare module.exports: $Exports<'nodegit/remote'>;
}
declare module 'nodegit/repository.js' {
  declare module.exports: $Exports<'nodegit/repository'>;
}
declare module 'nodegit/reset.js' {
  declare module.exports: $Exports<'nodegit/reset'>;
}
declare module 'nodegit/revert.js' {
  declare module.exports: $Exports<'nodegit/revert'>;
}
declare module 'nodegit/revwalk.js' {
  declare module.exports: $Exports<'nodegit/revwalk'>;
}
declare module 'nodegit/signature.js' {
  declare module.exports: $Exports<'nodegit/signature'>;
}
declare module 'nodegit/stash.js' {
  declare module.exports: $Exports<'nodegit/stash'>;
}
declare module 'nodegit/status_file.js' {
  declare module.exports: $Exports<'nodegit/status_file'>;
}
declare module 'nodegit/status_list.js' {
  declare module.exports: $Exports<'nodegit/status_list'>;
}
declare module 'nodegit/status.js' {
  declare module.exports: $Exports<'nodegit/status'>;
}
declare module 'nodegit/submodule.js' {
  declare module.exports: $Exports<'nodegit/submodule'>;
}
declare module 'nodegit/tag.js' {
  declare module.exports: $Exports<'nodegit/tag'>;
}
declare module 'nodegit/tree_entry.js' {
  declare module.exports: $Exports<'nodegit/tree_entry'>;
}
declare module 'nodegit/tree.js' {
  declare module.exports: $Exports<'nodegit/tree'>;
}
declare module 'nodegit/lookup_wrapper.js' {
  declare module.exports: $Exports<'nodegit/lookup_wrapper'>;
}
declare module 'nodegit/normalize_options.js' {
  declare module.exports: $Exports<'nodegit/normalize_options'>;
}
declare module 'nodegit/shallow_clone.js' {
  declare module.exports: $Exports<'nodegit/shallow_clone'>;
}
declare module 'nodegit/clean.js' {
  declare module.exports: $Exports<'nodegit/clean'>;
}
declare module 'nodegit/configureLibssh2.js' {
  declare module.exports: $Exports<'nodegit/configureLibssh2'>;
}
declare module 'nodegit/install.js' {
  declare module.exports: $Exports<'nodegit/install'>;
}
declare module 'nodegit/postinstall.js' {
  declare module.exports: $Exports<'nodegit/postinstall'>;
}
declare module 'nodegit/preinstall.js' {
  declare module.exports: $Exports<'nodegit/preinstall'>;
}
declare module 'nodegit/getStatus.js' {
  declare module.exports: $Exports<'nodegit/getStatus'>;
}
declare module 'nodegit/index' {
  declare module.exports: $Exports<'nodegit'>;
}
declare module 'nodegit/index.js' {
  declare module.exports: $Exports<'nodegit'>;
}
declare module 'nodegit/buildFlags.js' {
  declare module.exports: $Exports<'nodegit/buildFlags'>;
}
declare module 'nodegit/execPromise.js' {
  declare module.exports: $Exports<'nodegit/execPromise'>;
}
declare module 'nodegit/gitExecutableLocation.js' {
  declare module.exports: $Exports<'nodegit/gitExecutableLocation'>;
}
