// flow-typed signature: ed38f748888ad4c885c7907ad7bd0f2e
// flow-typed version: <<STUB>>/unzipper_v^0.10.8/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unzipper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unzipper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unzipper/lib/Buffer' {
  declare module.exports: any;
}

declare module 'unzipper/lib/BufferStream' {
  declare module.exports: any;
}

declare module 'unzipper/lib/Decrypt' {
  declare module.exports: any;
}

declare module 'unzipper/lib/extract' {
  declare module.exports: any;
}

declare module 'unzipper/lib/NoopStream' {
  declare module.exports: any;
}

declare module 'unzipper/lib/Open/directory' {
  declare module.exports: any;
}

declare module 'unzipper/lib/Open' {
  declare module.exports: any;
}

declare module 'unzipper/lib/Open/unzip' {
  declare module.exports: any;
}

declare module 'unzipper/lib/parse' {
  declare module.exports: any;
}

declare module 'unzipper/lib/parseDateTime' {
  declare module.exports: any;
}

declare module 'unzipper/lib/parseExtraField' {
  declare module.exports: any;
}

declare module 'unzipper/lib/parseOne' {
  declare module.exports: any;
}

declare module 'unzipper/lib/PullStream' {
  declare module.exports: any;
}

declare module 'unzipper/unzip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unzipper/lib/Buffer.js' {
  declare module.exports: $Exports<'unzipper/lib/Buffer'>;
}
declare module 'unzipper/lib/BufferStream.js' {
  declare module.exports: $Exports<'unzipper/lib/BufferStream'>;
}
declare module 'unzipper/lib/Decrypt.js' {
  declare module.exports: $Exports<'unzipper/lib/Decrypt'>;
}
declare module 'unzipper/lib/extract.js' {
  declare module.exports: $Exports<'unzipper/lib/extract'>;
}
declare module 'unzipper/lib/NoopStream.js' {
  declare module.exports: $Exports<'unzipper/lib/NoopStream'>;
}
declare module 'unzipper/lib/Open/directory.js' {
  declare module.exports: $Exports<'unzipper/lib/Open/directory'>;
}
declare module 'unzipper/lib/Open/index' {
  declare module.exports: $Exports<'unzipper/lib/Open'>;
}
declare module 'unzipper/lib/Open/index.js' {
  declare module.exports: $Exports<'unzipper/lib/Open'>;
}
declare module 'unzipper/lib/Open/unzip.js' {
  declare module.exports: $Exports<'unzipper/lib/Open/unzip'>;
}
declare module 'unzipper/lib/parse.js' {
  declare module.exports: $Exports<'unzipper/lib/parse'>;
}
declare module 'unzipper/lib/parseDateTime.js' {
  declare module.exports: $Exports<'unzipper/lib/parseDateTime'>;
}
declare module 'unzipper/lib/parseExtraField.js' {
  declare module.exports: $Exports<'unzipper/lib/parseExtraField'>;
}
declare module 'unzipper/lib/parseOne.js' {
  declare module.exports: $Exports<'unzipper/lib/parseOne'>;
}
declare module 'unzipper/lib/PullStream.js' {
  declare module.exports: $Exports<'unzipper/lib/PullStream'>;
}
declare module 'unzipper/unzip.js' {
  declare module.exports: $Exports<'unzipper/unzip'>;
}
