/**
 * Flowtype definitions for katex
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'katex' {
    declare interface KatexOptions {
        displayMode?: boolean,
            breakOnUnsupportedCmds?: boolean,
            errorColor?: string
    }
    declare class ParseError mixins Error {
        constructor(message: string, lexer: any, position: number): this;
        name: string;
        message: string;
        position: number
    }

    /**
     * Renders a TeX expression into the specified DOM element
     * @param tex A TeX expression
     * @param element The DOM element to render into
     * @param options KaTeX options
     */
    declare function render(tex: string, element: HTMLElement, options?: KatexOptions): void

    /**
     * Renders a TeX expression into an HTML string
     * @param tex A TeX expression
     * @param options KaTeX options
     */
    declare function renderToString(tex: string, options?: KatexOptions): string
}