/**
 * Flowtype definitions for lscache
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare interface LSCache {

    /**
     * Stores the value in localStorage. Expires after specified number of minutes.
     * @param  
     * @param  
     * @param  
     */
    set(key: string, value: any, time?: number): void,

        /**
         * Retrieves specified value from localStorage, if not expired.
         * @param  
         * @return  
         */
        get(key: string): any,

        /**
         * Removes a value from localStorage.
         * Equivalent to 'delete' in memcache, but that's a keyword in JS.
         * @param  
         */
        remove(key: string): void,

        /**
         * Flushes all lscache items and expiry markers without affecting rest of localStorage
         */
        flush(): void,

        /**
         * Flushes expired lscache items and expiry markers without affecting rest of localStorage
         */
        flushExpired(): void,

        /**
         * Appends CACHE_PREFIX so lscache will partition data in to different buckets.
         * @param  
         */
        setBucket(bucket: string): void,

        /**
         * Resets the string being appended to CACHE_PREFIX so lscache will use the default storage behavior.
         */
        resetBucket(): void
}
declare var lscache: LSCache;
declare module 'lscache' {
    declare var lscache: LSCache;
    declare module.exports: typeof lscache
}