// @flow
/**
 * Flowtype definitions for highcharts-more
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare var HighchartsMore: (H: ___Highcharts.Static) => ___Highcharts.Static;
declare module 'highcharts/highcharts-more' {
    declare module.exports: typeof HighchartsMore
}