// @flow
/**
 * Flowtype definitions for clone
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'clone' {
    declare module.exports: typeof clone

    declare     var npm$namespace$clone: {
            clonePrototype: typeof clone$clonePrototype,
        }
        /**
         * 
         * @param obj the object that you want to clone
         */
    declare     function clone$clonePrototype<T>(obj: T): T
}