/**
 * Flowtype definitions for byline
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'byline' {
    declare module.exports: typeof bl

    declare var npm$namespace$bl: {
        createStream: typeof bl$createStream,
    }
    declare export type bl$LineStreamOptions = {
        keepEmptyLines?: boolean
    }

    declare export type bl$LineStream = {}

    declare export type bl$LineStreamCreatable = {
        new(options?: bl$LineStreamOptions): bl$LineStream
    } & bl$LineStream


    declare export function bl$createStream(): bl$LineStream

    declare export var LineStream: bl$LineStreamCreatable;
}