/**
 * Flowtype definitions for gulp-dtsm
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'gulp-dtsm' {
    declare module.exports: typeof dtsm

}