// @flow
/**
 * Flowtype definitions for dot-prop
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'dot-prop' {
    declare     export function get(object: any, path: string): any
    declare     export function set(object: any, path: string, value: any): void
}