/**
 * Flowtype definitions for buffer-equal
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'buffer-equal' {
    declare module.exports: typeof bufferEqual
}