// @flow
/**
 * Flowtype definitions for title-case
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'title-case' {
    declare module.exports: typeof titleCase
}