// @flow
/**
 * Flowtype definitions for pi-spi
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */


declare var npm$namespace$___PI_SPI: {
    initialize: typeof ___PI_SPI$initialize,
}
declare function ___PI_SPI$initialize(device: string): ___PI_SPI$SPI

declare class SPI {
    clockSpeed(): number;
    clockSpeed(speed: number): void;
    dataMode(): number;
    dataMode(mode: mode): void;
    bitOrder(): number;
    bitOrder(order: order): void;
    write(writebuf: Buffer, cb: (error: Error, data: Buffer) => void): void;
    read(readcount: number, cb: (error: Error, data: Buffer) => void): void;
    transfer(writebuf: Buffer, cb: (error: Error, data: Buffer) => void): void;
    transfer(
        writebuf: Buffer,
        readcount: number,
        cb: (error: Error, data: Buffer) => void): void;
    close(): void
}
declare module 'pi-spi' {
    declare module.exports: typeof ___PI_SPI
}