

declare module 'is_js' {
		declare interface IsStatic {
		arguments(value: any): boolean,
		array(value: any): boolean,
		boolean(value: any): boolean,
		date(value: any): boolean,
		error(value: any): boolean,
		function(value: any): boolean,
		nan(value: any): boolean,
		null(value: any): boolean,
		number(value: any): boolean,
		object(value: any): boolean,
		json(value: any): boolean,
		regexp(value: any): boolean,
		string(value: any): boolean,
		char(value: any): boolean,
		undefined(value: any): boolean,
		sameType(value1: any, value2: any): boolean,
		empty(value: any): boolean,
		existy(value: any): boolean,
		truthy(value: any): boolean,
		falsy(value: any): boolean,
		space(value: any): boolean,
		url(value: any): boolean,
		email(value: any): boolean,
		creditCard(value: any): boolean,
		alphaNumeric(value: any): boolean,
		timeString(value: any): boolean,
		dateString(value: any): boolean,
		usZipCode(value: any): boolean,
		caPostalCode(value: any): boolean,
		ukPostCode(value: any): boolean,
		nanpPhone(value: any): boolean,
		eppPhone(value: any): boolean,
		socialSecurityNumber(value: any): boolean,
		affirmative(value: any): boolean,
		hexadecimal(value: any): boolean,
		hexColor(value: any): boolean,
		ip(value: any): boolean,
		ipv4(value: any): boolean,
		ipv6(value: any): boolean,
		include(value1: string, value2: string): boolean,
		upperCase(value: string): boolean,
		lowerCase(value: string): boolean,
		startWith(value1: string, value2: string): boolean,
		endWith(value1: string, value2: string): boolean,
		capitalized(value: string): boolean,
		palindrome(value: string): boolean,
		equal(value1: any, value2: any): boolean,
		even(value: number): boolean,
		odd(value: number): boolean,
		positive(value: number): boolean,
		negative(value: number): boolean,
		above(value: number, min: number): boolean,
		under(value: number, max: number): boolean,
		within(value: number, min: number, max: number): boolean,
		decimal(value: number): boolean,
		integer(value: number): boolean,
		finite(value: number): boolean,
		infinite(value: number): boolean,
		propertyCount(value: any, count: number): boolean,
		propertyDefined(value: any, property: string): boolean,
		windowObject(value: any): boolean,
		domNode(value: any): boolean,
		inArray<T>(value: T, array: T[]): boolean,
		sorted(value: any[]): boolean,
		ie(value?: number): boolean,
		chrome(): boolean,
		firefox(): boolean,
		opera(): boolean,
		safari(): boolean,
		ios(): boolean,
		iphone(): boolean,
		ipad(): boolean,
		ipod(): boolean,
		android(): boolean,
		androidPhone(): boolean,
		androidTablet(): boolean,
		blackberry(): boolean,
		windowsPhone(): boolean,
		windowsTablet(): boolean,
		windows(): boolean,
		mac(): boolean,
		linux(): boolean,
		desktop(): boolean,
		mobile(): boolean,
		tablet(): boolean,
		online(): boolean,
		offline(): boolean,
		today(value: Date): boolean,
		yesterday(value: Date): boolean,
		tomorrow(value: Date): boolean,
		past(value: Date): boolean,
		future(value: Date): boolean,
		day(value: Date, dayString: string): boolean,
		month(value: Date, monthString: string): boolean,
		year(value: Date, yearNumber: number): boolean,
		leapYear(value: number): boolean,
		weekend(value: Date): boolean,
		weekday(value: Date): boolean,
		inDateRange(value: Date, start: Date, end: Date): boolean,
		inLastWeek(value: Date): boolean,
		inLastMonth(value: Date): boolean,
		inLastYear(value: Date): boolean,
		inNextWeek(value: Date): boolean,
		inNextMonth(value: Date): boolean,
		inNextYear(value: Date): boolean,
		quarterOfYear(value: Date, quarter: number): boolean,
		dayLightSavingTime(value: Date): boolean
	}

	declare interface IsStaticApi {
		arguments(...value: any[]): boolean,
		arguments(value: any[]): boolean,
		array(...value: any[]): boolean,
		array(value: any[]): boolean,
		boolean(...value: any[]): boolean,
		boolean(value: any[]): boolean,
		date(...value: any[]): boolean,
		date(value: any[]): boolean,
		error(...value: any[]): boolean,
		error(value: any[]): boolean,
		function(...value: any[]): boolean,
		function(value: any[]): boolean,
		nan(...value: any[]): boolean,
		nan(value: any[]): boolean,
		null(...value: any[]): boolean,
		null(value: any[]): boolean,
		number(...value: any[]): boolean,
		number(value: any[]): boolean,
		object(...value: any[]): boolean,
		object(value: any[]): boolean,
		json(...value: any[]): boolean,
		json(value: any[]): boolean,
		regexp(...value: any[]): boolean,
		regexp(value: any[]): boolean,
		string(...value: any[]): boolean,
		string(value: any[]): boolean,
		char(...value: any[]): boolean,
		char(value: any[]): boolean,
		undefined(...value: any[]): boolean,
		undefined(value: any[]): boolean,
		empty(...value: any[]): boolean,
		empty(value: any[]): boolean,
		existy(...value: any[]): boolean,
		existy(value: any[]): boolean,
		truthy(...value: any[]): boolean,
		truthy(value: any[]): boolean,
		falsy(...value: any[]): boolean,
		falsy(value: any[]): boolean,
		space(...value: any[]): boolean,
		space(value: any[]): boolean,
		url(...value: any[]): boolean,
		url(value: any[]): boolean,
		email(...value: any[]): boolean,
		email(value: any[]): boolean,
		creditCard(...value: any[]): boolean,
		creditCard(value: any[]): boolean,
		alphaNumeric(...value: any[]): boolean,
		alphaNumeric(value: any[]): boolean,
		timeString(...value: any[]): boolean,
		timeString(value: any[]): boolean,
		dateString(...value: any[]): boolean,
		dateString(value: any[]): boolean,
		usZipCode(...value: any[]): boolean,
		usZipCode(value: any[]): boolean,
		caPostalCode(...value: any[]): boolean,
		caPostalCode(value: any[]): boolean,
		ukPostCode(...value: any[]): boolean,
		ukPostCode(value: any[]): boolean,
		nanpPhone(...value: any[]): boolean,
		nanpPhone(value: any[]): boolean,
		eppPhone(...value: any[]): boolean,
		eppPhone(value: any[]): boolean,
		socialSecurityNumber(...value: any[]): boolean,
		socialSecurityNumber(value: any[]): boolean,
		affirmative(...value: any[]): boolean,
		affirmative(value: any[]): boolean,
		hexadecimal(...value: any[]): boolean,
		hexadecimal(value: any[]): boolean,
		hexColor(...value: any[]): boolean,
		hexColor(value: any[]): boolean,
		ip(...value: any[]): boolean,
		ip(value: any[]): boolean,
		ipv4(...value: any[]): boolean,
		ipv4(value: any[]): boolean,
		ipv6(...value: any[]): boolean,
		ipv6(value: any[]): boolean,
		upperCase(...value: string[]): boolean,
		upperCase(value: string[]): boolean,
		lowerCase(...value: string[]): boolean,
		lowerCase(value: string[]): boolean,
		capitalized(...value: string[]): boolean,
		capitalized(value: string[]): boolean,
		palindrome(...value: string[]): boolean,
		palindrome(value: string[]): boolean,
		even(...value: number[]): boolean,
		even(value: number[]): boolean,
		odd(...value: number[]): boolean,
		odd(value: number[]): boolean,
		positive(...value: number[]): boolean,
		positive(value: number[]): boolean,
		negative(...value: number[]): boolean,
		negative(value: number[]): boolean,
		decimal(...value: number[]): boolean,
		decimal(value: number[]): boolean,
		integer(...value: number[]): boolean,
		integer(value: number[]): boolean,
		finite(...value: number[]): boolean,
		finite(value: number[]): boolean,
		infinite(...value: number[]): boolean,
		infinite(value: number[]): boolean,
		windowObject(...value: any[]): boolean,
		windowObject(value: any[]): boolean,
		domNode(...value: any[]): boolean,
		domNode(value: any[]): boolean,
		sorted(...value: number[][]): boolean,
		sorted(value: number[][]): boolean,
		today(...value: Date[]): boolean,
		today(value: Date[]): boolean,
		yesterday(...value: Date[]): boolean,
		yesterday(value: Date[]): boolean,
		tomorrow(...value: Date[]): boolean,
		tomorrow(value: Date[]): boolean,
		past(...value: Date[]): boolean,
		past(value: Date[]): boolean,
		future(...value: Date[]): boolean,
		future(value: Date[]): boolean,
		leapYear(...value: number[]): boolean,
		leapYear(value: number[]): boolean,
		weekend(...value: Date[]): boolean,
		weekend(value: Date[]): boolean,
		weekday(...value: Date[]): boolean,
		weekday(value: Date[]): boolean
	}

	declare interface Is {
		not: IsStatic,
		any: IsStaticApi,
		all: IsStaticApi,
		setRegexp(value: RegExp, regexp: "url"): boolean,
		setRegexp(value: RegExp, regexp: "email"): boolean,
		setRegexp(value: RegExp, regexp: "creditCard"): boolean,
		setRegexp(value: RegExp, regexp: "alphaNumeric"): boolean,
		setRegexp(value: RegExp, regexp: "timeString"): boolean,
		setRegexp(value: RegExp, regexp: "dateString"): boolean,
		setRegexp(value: RegExp, regexp: "usZipCode"): boolean,
		setRegexp(value: RegExp, regexp: "caPostalCode"): boolean,
		setRegexp(value: RegExp, regexp: "nanpPhone"): boolean,
		setRegexp(value: RegExp, regexp: "eppPhone"): boolean,
		setRegexp(value: RegExp, regexp: "affirmative"): boolean,
		setRegexp(value: RegExp, regexp: "hexadecimal"): boolean,
		setRegexp(value: RegExp, regexp: "hexColor"): boolean,
		setRegexp(value: RegExp, regexp: "ip"): boolean,
		setRegexp(value: RegExp, regexp: "ipv6"): boolean,
		setRegexp(value: RegExp, regexp: string): boolean,
		setNamespace(): Is
	}

			
}

declare module 'is' {
					declare module.exports: undefined


}