/**
 * Flowtype definitions for google-apps-script.types
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare type GoogleAppsScript$BigNumber = any;

declare type GoogleAppsScript$Byte = number;

declare type GoogleAppsScript$Integer = number;

declare type GoogleAppsScript$Char = string;

declare type GoogleAppsScript$JdbcSQL_XML = any;