/**
 * Flowtype definitions for svgjs.resize
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare
export interface svgjs$Element {
    selectize(): svgjs$Element,
        selectize(obj: Object): svgjs$Element,
        resize(): svgjs$Element,
        resize(obj: Object): svgjs$Element
}