/**
 * Flowtype definitions for lolex
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'lolex' {
    declare export interface Clock {
        setTimeout(callback: () => any, timeout: number): number,
            setInterval(callback: () => any, timeout: number): number,
            setImmediate(callback: () => any): number,
            clearTimeout(id: number): void,
            clearInterval(id: number): void,
            clearImmediate(id: number): void,
            tick(ms: number): void,
            uninstall(): void
    }
    declare export function createClock(now?: number): Clock
    declare export function install(now?: number, toFake?: string[]): Clock
}