/**
 * Flowtype definitions for ng-dialog
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'ng-dialog' {
    declare export type IDialogService = undefined.IDialogService;
    declare export type IDialogOpenResult = undefined.IDialogOpenResult;
    declare export type IDialogClosePromise = undefined.IDialogClosePromise;
    declare export type IDialogProvider = undefined.IDialogProvider;
    declare export type IDialogScope = undefined.IDialogScope;
    declare export type IDialogConfirmScope = undefined.IDialogConfirmScope;
    declare export type IDialogOptions = undefined.IDialogOptions;
    declare export type IDialogOpenOptions = undefined.IDialogOpenOptions;
    declare export type IDialogOpenConfirmOptions = undefined.IDialogOpenConfirmOptions;
}
declare module 'dialog' {
    declare export type IDialogService = undefined.IDialogService;
    declare export type IDialogOpenResult = undefined.IDialogOpenResult;
    declare export type IDialogClosePromise = undefined.IDialogClosePromise;
    declare export type IDialogProvider = undefined.IDialogProvider;
    declare export type IDialogScope = undefined.IDialogScope;
    declare export type IDialogConfirmScope = undefined.IDialogConfirmScope;
    declare export type IDialogOptions = undefined.IDialogOptions;
    declare export type IDialogOpenOptions = undefined.IDialogOpenOptions;
    declare export type IDialogOpenConfirmOptions = undefined.IDialogOpenConfirmOptions;
}