/**
 * Flowtype definitions for angular-cookies-1.2
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'cookies' {
    declare interface ICookiesService {}
    declare interface ICookieStoreService {

        /**
         * Returns the value of given cookie key
         * @param key Id to use for lookup
         */
        get(key: string): any,

            /**
             * Sets a value for given cookie key
             * @param key Id for the value
             * @param value Value to be stored
             */
            put(key: string, value: any): void,

            /**
             * Remove given cookie
             * @param key Id of the key-value pair to delete
             */
            remove(key: string): void
    }
}