/**
 * Flowtype definitions for dot
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare var doT: doT$doTStatic;
declare interface doT$doTStatic {

    /**
     * Version number
     */
    version: string,

        /**
         * Default template settings
         */
        templateSettings: doT$TemplateSettings,

        /**
         * Compile template
         */
        template(tmpl: string, c?: doT$TemplateSettings, def?: Object): Function,

        /**
         * For express
         */
        compile(tmpl: string, def?: Object): Function
}

declare interface doT$TemplateSettings {
    evaluate: RegExp,
        interpolate: RegExp,
        encode: RegExp,
        use: RegExp,
        useParams: RegExp,
        define: RegExp,
        defineParams: RegExp,
        conditional: RegExp,
        iterate: RegExp,
        varname: string,
        strip: boolean,
        append: boolean,
        selfcontained: boolean
}
declare interface String {
    encodeHTML(): string
}