// @flow
/**
 * Flowtype definitions for babelify
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'babelify' {
    declare module.exports: typeof Babelify
}