// @flow
/**
 * Flowtype definitions for git-config
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'git-config' {
    declare     export function sync(gitFile?: string): Object
}