/**
 * Flowtype definitions for gulp-insert
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'gulp-insert' {
    declare interface Transformer {
        (contents: string, file: File): string
    }

    declare var npm$namespace$Insert: {
            prepend: typeof Insert$prepend,
            append: typeof Insert$append,
            wrap: typeof Insert$wrap,
            transform: typeof Insert$transform,
        }
        /**
         * Prepends a string onto the contents
         * @param  
         * @returns  
         */
    declare function Insert$prepend(content: string): NodeJS.ReadWriteStream


    /**
     * Appends a string onto the contents
     * @param  
     * @returns  
     */
    declare function Insert$append(content: string): NodeJS.ReadWriteStream


    /**
     * Wraps the contents with two strings
     * @param  
     * @param  
     * @returns  
     */
    declare function Insert$wrap(prepend: string, append: string): NodeJS.ReadWriteStream


    /**
     * Calls a function with the contents of the file
     * @param  
     * @returns  
     */
    declare function Insert$transform(transformer: Transformer): NodeJS.ReadWriteStream
    declare module.exports: typeof Insert
}