// @flow
/**
 * Flowtype definitions for split2
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'split2' {

    declare type Matcher = string | RegExp;
    declare type Mapper = split$Mapper;
    declare type Options = split$Options;
    declare module.exports: typeof split
    declare type split$Mapper = split$Mapper;

    declare type split$Options = split$Options;
}