/**
 * Flowtype definitions for ndarray
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'ndarray' {
    declare type Data = Array<number >
        |
        Int8Array |
        Int16Array |
        Int32Array |
        Uint8Array |
        Uint16Array |
        Uint32Array |
        Float32Array |
        Float64Array |
        Uint8ClampedArray;
    declare module.exports: typeof ndarray

}