/**
 * Flowtype definitions for tracking
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */


declare var npm$namespace$tracking: {
    track: typeof tracking$track,
}
declare export class ColorTracker mixins Tracker {
    constructor(colours: string[]): this;
    registerColor(name: string, predicate: (r: number, g: number, b: number) => boolean): void
}

declare export class ObjectTracker mixins Tracker {
    constructor(objects: string[]): this
}

declare class Tracker {
    constructor(target: string): this;
    on(eventName: string, callback: (event: tracking$TrackEvent) => void): void
}

declare interface tracking$TrackEvent {
    data: tracking$TrackRect[]
}

declare interface tracking$TrackRect {
    x: number,
        y: number,
        height: number,
        width: number,
        color: string
}

declare interface tracking$TrackerTask {
    stop(): void,
        run(): void
}

declare export function tracking$track(selector: string, tracker: tracking$Tracker): tracking$TrackerTask