// @flow
/**
 * Flowtype definitions for type-detect
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'type-detect' {
    declare module.exports: typeof type
    declare     export class Library { of (val: any): string;
        define(type: string, test: RegExp): void;
        define(type: string, test: (val: any) => boolean): void;
        test(val: any, type: string): boolean
    }
}