/**
 * Flowtype definitions for highlightjs-7.5.0
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'highlight.js' {

    declare var npm$namespace$hljs: {
        blockText: typeof hljs$blockText,
        blockLanguage: typeof hljs$blockLanguage,
        highlight: typeof hljs$highlight,
        highlightAuto: typeof hljs$highlightAuto,
        fixMarkup: typeof hljs$fixMarkup,
        highlightBlock: typeof hljs$highlightBlock,
        initHighlighting: typeof hljs$initHighlighting,
        initHighlightingOnLoad: typeof hljs$initHighlightingOnLoad,
    }
    declare export var LANGUAGES: {
        [name: string]: any
    };

    declare export function hljs$blockText(block: Node, ignoreNewLines: boolean): string

    declare export function hljs$blockLanguage(block: Node): string

    declare export function hljs$highlight(language_name: string, value: string): hljs$IHighlightResult

    declare export function hljs$highlightAuto(text: string): hljs$IHighlightResult

    declare export function hljs$fixMarkup(value: string, tabReplace: boolean, useBR: boolean): string

    declare export function hljs$highlightBlock(block: Node, tabReplace?: boolean, useBR?: boolean): void

    declare export function hljs$initHighlighting(): void

    declare export function hljs$initHighlightingOnLoad(): void

    declare export var tabReplace: string;

    declare export var IDENT_RE: string;

    declare export var UNDERSCORE_IDENT_RE: string;

    declare export var NUMBER_RE: string;

    declare export var C_NUMBER_RE: string;

    declare export var BINARY_NUMBER_RE: string;

    declare export var RE_STARTERS_RE: string;

    declare export var BACKSLASH_ESCAPE: hljs$IMode;

    declare export var APOS_STRING_MODE: hljs$IMode;

    declare export var QUOTE_STRING_MODE: hljs$IMode;

    declare export var C_LINE_COMMENT_MODE: hljs$IMode;

    declare export var C_BLOCK_COMMENT_MODE: hljs$IMode;

    declare export var HASH_COMMENT_MODE: hljs$IMode;

    declare export var NUMBER_MODE: hljs$IMode;

    declare export var C_NUMBER_MODE: hljs$IMode;

    declare export var BINARY_NUMBER_MODE: hljs$IMode;

    declare export interface hljs$IHighlightResult {
        relevance: number,
            keyword_count: number,
            value: string
    }

    declare export type hljs$IAutoHighlightResult = {
        language: string,
        second_best?: hljs$IAutoHighlightResult
    } & hljs$IHighlightResult


    declare export interface hljs$IMode {
        className?: string,
            begin: string,
            end?: string,
            beginWithKeyword?: boolean,
            endsWithParent?: boolean,
            lexems?: string,
            keywords?: Object,
            illegal?: string,
            excludeBegin?: boolean,
            excludeEnd?: boolean,
            returnBegin?: boolean,
            returnEnd?: boolean,
            contains?: hljs$IMode[],
            starts?: string,
            subLanguage?: string,
            relevance?: number
    }
    declare module.exports: typeof hljs
}