/**
 * Flowtype definitions for envify
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'envify' {
    declare var envify: (file: string, environment: {
        [name: string]: any
    }) => NodeJS.ReadWriteStream;
    declare module.exports: typeof envify
}
declare module 'envify/custom' {
    declare module.exports: typeof envify
}