// @flow
/**
 * Flowtype definitions for ng-i18next
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'i18next' {
    declare interface I18nextProvider {
        options: I18nextOptions
    }
}