// @flow
/**
 * Flowtype definitions for koa-hbs
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'koa-hbs' {


    declare module.exports: typeof Hbs
}