/**
 * Flowtype definitions for file-type
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'file-type' {
    declare interface FileTypeResult {
        ext: string,
            mime: string
    }
    declare module.exports: typeof FileType
}