/**
 * Flowtype definitions for adal-angular
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare interface adal$AdalAuthenticationServiceProvider {
    init(configOptions: Config, httpProvider: angular.IHttpProvider): void
}

declare interface adal$UserInfo {
    isAuthenticated: boolean,
        userName: string,
        loginError: string,
        profile: any
}

declare interface adal$AdalAuthenticationService {
    config: Config,
        userInfo: adal$UserInfo,
        login(): void,
        loginInProgress(): boolean,
        logOut(): void,
        getCachedToken(resource: string): string,
        acquireToken(resource: string): angular.IPromise<string>,
        getUser(): angular.IPromise<User>,
        getResourceForEndpoint(endpoint: string): string,
        clearCache(): void,
        clearCacheForResource(resource: string): void,
        info(message: string): void,
        verbose(message: string): void
}