/**
 * Flowtype definitions for react-tabs
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare interface ReactTabs$TabsProps {
    className?: string,
        selectedIndex?: number,
        focus?: boolean,
        forceRenderTabPanel?: boolean,
        onSelect?: (index: number, last: number) => void
}

declare type ReactTabs$Tabs = {
    setUseDefaultStyles: (use: boolean) => void
}

declare interface ReactTabs$TabListProps {
    className?: string,
        activeTabClassName?: string,
        disabledTabClassName?: string
}

declare type ReactTabs$TabList = {}

declare interface ReactTabs$TabProps {
    className?: string,
        focus?: boolean,
        selected?: boolean,
        id?: string,
        panelId?: string
}

declare type ReactTabs$Tab = {}

declare interface ReactTabs$TabPanelProps {
    className?: string,
        selected?: boolean,
        id?: string,
        tabId?: string
}

declare type ReactTabs$TabPanel = {}
declare module 'react-tabs' {
    declare var Tabs: ReactTabs$Tabs;
    declare var TabList: ReactTabs$TabList;
    declare var Tab: ReactTabs$Tab;
    declare var TabPanel: ReactTabs$TabPanel;
}