/**
 * Flowtype definitions for fromnow
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare interface FromNow$FromNowOpts {
    maxChunks?: number,
        useAgo?: boolean,
        useAnd?: boolean
}

declare
export interface FromNow$FromNowStatic {

    /**
     * Get readable time differences from now vs past or future dates.
     * @param  
     * @param  * 
     * @param  .maxChucks=10]
     * @param  .useAgo=false]
     * @param  .useAnd=false]
     */
    (date: string | Date, opts?: FromNow$FromNowOpts): string
}
declare module 'fromnow' {
    declare var FromNow: FromNow$FromNowStatic;
    declare module.exports: typeof FromNow
}