/**
 * Flowtype definitions for dom4
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.0.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare interface ParentNode {

    /**
     * Returns the child elements.
     */
    children: HTMLCollection,

        /**
         * Returns the first element that is a descendant of node that matches relativeSelectors.
         */
        query(relativeSelectors: string): Element,

        /**
         * Returns all element descendants of node that match relativeSelectors.
         */
        queryAll(relativeSelectors: string): Elements
}
declare type Element = {

    /**
     * Returns the first (starting at element) inclusive ancestor that matches selectors, and null otherwise.
     */
    closest(selectors: string): Element,

    /**
     * Returns true if matching selectors against element’s root yields element, and false otherwise.
     */
    matches(selectors: string): boolean
} & ParentNode
declare type Elements = {} & ElementTraversal & ParentNode & Array
declare type Document = {} & ElementTraversal & ParentNode
declare type DocumentFragment = {} & ElementTraversal & ParentNode